---
- name: Iptables - Install pip
  ansible.builtin.yum:
    name:
      - python3-pip
    state: present

- name: Iptables - Get python executable
  shell: |
    set -o pipefail
    ls -l /usr/bin/python3.* | grep -E "python[0-9].[0-9]{1,2}$" | awk '{print $9}' | tail -n1
  args:
    executable: /bin/bash
  become: true
  register: python3_which
  changed_when: false
  tags:
    - iptables_install

- name: Iptables - Install from pip
  shell: |
    set -o pipefail
    {{ python3_which.stdout }} -m pip install --proxy={{ proxy }} --upgrade --force-reinstall {{ pip_packages | join( ' ') }}
  args:
    executable: /bin/bash
  changed_when: false
  tags:
    - iptables_install